//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libro
    {
        [ScaffoldColumn(false)]
        public int id_lib { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El Titulo es Requerido"), MaxLength(55)]
        [Display(Name = "Titulo")]
        public string titulo_lib { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El Autor es Requerido"), MaxLength(55)]
        [Display(Name = "Autor")]
        public string autor_lib { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [Display(Name = "Fecha de Publicación")]
        public Nullable<System.DateTime> fecha_publicacion_lib { get; set; }

        [Display(Name = "Número de Ejemplares")]
        public Nullable<int> num_lib { get; set; }
        public Nullable<int> id_cat { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
